[theme]
primaryColor="#32c800"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#fdfdfd"
font="serif"
language="toml"

--theme.primaryColor="#32c800"
--theme.backgroundColor="#252323"
--theme.secondaryBackgroundColor="#000000"
--theme.textColor="#fdfdfd"
--theme.font="serif"
